services:
  neo4j:
    image: neo4j:latest  # Use the official Neo4j Docker image
    container_name: neo
    ports:
      - "7474:7474"  # Neo4j Browser (HTTP)
      - "7687:7687"  # Bolt protocol (driver connections)
    environment:
      - NEO4J_AUTH=neo4j/testtest  # Set username and password (format: NEO4J_AUTH=user/password)
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - ./neo4j/data:/data   # Persist database data
      - ./neo4j/import:/var/lib/neo4j/import  # Directory for importing data
      - ./neo4j/plugins:/plugins  # For custom plugins
      - ./neo4j/conf:/var/lib/neo4j/conf/  # Configuration file